### ISSUE TITLE
Python API Orderstatus call error

### ISSUE THREAD

**Issue by hemangshah36** [marketcalls/openalgo#688]
Broker: Wisdom Capital (XTS API)

This is given in help docs.

https://docs.openalgo.in/trading-platform/python#orderstatus-example

`response = client.orderstatus(
order_id="250828000185002",
strategy="Test Strategy"
)
print(response)`

`{
"data": {
"action": "BUY",
"average_price": 18.95,
"exchange": "NSE",
"order_status": "complete",
"orderid": "250828000185002",
"price": 0,
"pricetype": "MARKET",
"product": "MIS",
"quantity": "1",
"symbol": "YESBANK",
"timestamp": "28-Aug-2025 09:59:10",
"trigger_price": 0
},
"status": "success"
}`

So average_price": 18.95, is actual average fill price though trigger_price": 0.

However, in actual, both are shown as ZERO.

This is live log from openalgo (LIVE mode; the order went through broker as well but still showing zero).

`{
  "action": "BUY",
  "exchange": "NSE",
  "pricetype": "MARKET",
  "product": "MIS",
  "quantity": "15",
  "strategy": "TV_Screener_Live",
  "symbol": "IPL"
}`

`{
  "orderid": 1110913228,
  "status": "success"
}`

`{
  "orderid": "1110913228",
  "strategy": "Python"
}`

`{
  "data": {
    "action": "BUY",
    "**average_price": 0.0,**
    "exchange": "NSE",
    "order_status": "complete",
    "orderid": "1110913228",
    "price": 0.0,
    "pricetype": "MARKET",
    "product": "MIS",
    "quantity": 15,
    "symbol": "IPL",
    "timestamp": "29-12-2025 11:10:38",
    "**trigger_price": 0.0**
  },
  "status": "success"
}`

**It is necessary to get actual fill price to set target / SL in algo.

Please rectify and/or suggest alternative mechanism to get fill price to make strategy work.**

**Comment by Azhagesan-dev** [comment]
To get actual fill price use "tradebook" api, https://docs.openalgo.in/trading-platform/python#tradebook-example
Orderbook only contains order related detailed, fill prices not reflected in it.

**Comment by marketcalls** [comment]
> To get actual fill price use "tradebook" api, https://docs.openalgo.in/trading-platform/python#tradebook-example Orderbook only contains order related detailed, fill prices not reflected in it.

average_price contains the executed price in the order status. 

@hemangshah36 will look into it shortly.

**Comment by hemangshah36** [comment]
> To get actual fill price use "tradebook" api, https://docs.openalgo.in/trading-platform/python#tradebook-example Orderbook only contains order related detailed, fill prices not reflected in it.

@Azhagesan-dev - NO, unfortunately, tradebook API will NOT serve the purpose. If we have taken multiple entries for same symbol in a day, tradebook API returns average price of all orders taken together. What my requirement is to know the price at which my last market order was executed to decide target & SL. Taking day average price will be misleading. Same is the limitation with position status api as well.

@marketcalls - Due to above stated reason, it is humbly requested to solve this bug.

**Comment by marketcalls** [comment]
The PR is fixed https://github.com/marketcalls/openalgo/pull/690 we are testing before releasing it

**Comment by marketcalls** [comment]
This issue is sorted out in the PR https://github.com/marketcalls/openalgo/pull/690
kindly pull the latest commit and check it out

**Comment by Kalaiviswa** [comment]
{
  "data": {
    "action": "BUY",
    "average_price": 0.0,
    "exchange": "NSE",
    "order_status": "rejected",
    "orderid": 1110042730.0,
    "price": 21.62,
    "pricetype": "SL",
    "product": "MIS",
    "quantity": 1,
    "symbol": "YESBANK",
    "timestamp": "31-12-2025 13:12:55",
    "trigger_price": 21.65
  },
  "status": "success"
}

{
  "data": {
    "action": "BUY",
    "average_price": 21.67,
    "exchange": "NSE",
    "order_status": "complete",
    "orderid": 1110042731.0,
    "price": 21.68,
    "pricetype": "LIMIT",
    "product": "MIS",
    "quantity": 1,
    "symbol": "YESBANK",
    "timestamp": "31-12-2025 13:17:26",
    "trigger_price": 0.0
  },
  "status": "success"
}

{"LoginID":"KAR51","ClientID":"KAR51","AppOrderID":1110042730,"OrderReferenceID":"","GeneratedBy":"TWSAPI","ExchangeOrderID":"","OrderCategoryType":"NORMAL","ExchangeSegment":"NSECM","ExchangeInstrumentID":11915,"OrderSide":"BUY","OrderType":"StopLimit","ProductType":"MIS","TimeInForce":"DAY","OrderPrice":21.62,"OrderQuantity":1,"OrderStopPrice":21.65,"OrderStatus":"Rejected","OrderAverageTradedPrice":"","LeavesQuantity":1,"CumulativeQuantity":0,"OrderDisclosedQuantity":0,"OrderGeneratedDateTime":"31-12-2025 13:12:55","ExchangeTransactTime":"31-12-2025 13:12:55","TradingSymbol":"YESBANK","LastUpdateDateTime":"31-12-2025 13:12:55","OrderExpiryDate":"01-01-1980 00:00:00","CancelRejectReason":"Gateway:Trigger Price cannot be greater than Limit Price.","OrderUniqueIdentifier":"openalgo","OrderLegStatus":"SingleOrderLeg","BoLegDetails":0,"IsSpread":false,"BoEntryOrderId":"","ApiOrderSource":"","MessageCode":9004,"MessageVersion":4,"TokenID":0,"ApplicationType":0,"SequenceNumber":0}

{'LoginID': 'KAR51', 'ClientID': 'KAR51', 'AppOrderID': 1110042731, 'OrderReferenceID': '', 'GeneratedBy': 'TWSAPI', 'ExchangeOrderID': '1300000042403527', 'OrderCategoryType': 'NORMAL', 'ExchangeSegment': 'NSECM', 'ExchangeInstrumentID': 11915, 'OrderSide': 'BUY', 'OrderType': 'Limit', 'ProductType': 'MIS', 'TimeInForce': 'DAY', 'OrderPrice': 0, 'OrderQuantity': 1, 'OrderStopPrice': 0, 'OrderStatus': 'Filled', 'OrderAverageTradedPrice': '21.67', 'LeavesQuantity': 0, 'CumulativeQuantity': 1, 'OrderDisclosedQuantity': 0, 'OrderGeneratedDateTime': '31-12-2025 13:14:08', 'ExchangeTransactTime': '31-12-2025 13:17:26', 'LastUpdateDateTime': '31-12-2025 13:17:26', 'OrderUniqueIdentifier': 'openalgo', 'OrderLegStatus': 'SingleOrderLeg', 'LastTradedPrice': 21.67, 'LastTradedQuantity': 1, 'LastExecutionTransactTime': '31-12-2025 13:17:26', 'ExecutionID': '604951948', 'TradingSymbol': 'YESBANK', 'ExecutionReportIndex': 7, 'ApiOrderSource': '', 'IsSpread': False, 'MessageCode': 9005, 'MessageVersion': 4, 'TokenID': 0, 'ApplicationType': 0, 'SequenceNumber': 0}

logs obtained

**Comment by hemangshah36** [comment]
@marketcalls @Kalaiviswa 

It's not fully resolved.

`response = client.orderstatus(
    order_id="1110925155",
    strategy="Test Strategy"
    )
print(response)`

```
(venv) PS C:\tv_screener_api> python test.py
{'data': {'action': 'BUY', 'average_price': 0.0, 'exchange': 'NSE', 'order_status': 'complete', 'orderid': '1110925155', 'price': 0.0, 'pricetype': 'MARKET', 'product': 'MIS', 'quantity': 101, 'symbol': 'UCOBANK', 'timestamp': '31-12-2025 12:44:41', 'trigger_price': 0.0}, 'status': 'success'}
```

Though Openalgo console log shows average price, python api call response = client.orderstatus is NOT able to fetch it.


[2025-12-31 23:34:20,892] INFO in orderstatus_service: [OrderStatus] Processing order status request - Mode: LIVE, OrderID: 1110925155.0, Broker: wisdom  
[2025-12-31 23:34:21,342] INFO in orderstatus_service: [OrderStatus] Searching for OrderID 1110925155.0 in 3 orders from orderbook
[2025-12-31 23:34:21,343] WARNING in orderstatus_service: [OrderStatus] Order 1110925155.0 not found in orderbook after searching 3 orders
[2025-12-31 23:34:47,517] INFO in process: t=2025-12-31T23:34:47+0530 lvl=info msg="join connections" obj=join id=d9c188e89ed8 l=127.0.0.1:5000 r=49.36.73.94:55051
[2025-12-31 23:35:12,231] INFO in orderstatus_service: [OrderStatus] Processing order status request - Mode: LIVE, OrderID: 1110925155, Broker: wisdom    
[2025-12-31 23:35:12,379] INFO in orderstatus_service: [OrderStatus] Searching for OrderID 1110925155 in 3 orders from orderbook
[2025-12-31 23:35:12,380] INFO in orderstatus_service: [OrderStatus] Found matching order - Symbol: UCOBANK, Status: complete, Price: 0.0
[2025-12-31 23:35:12,381] INFO in orderstatus_service: [OrderStatus] Order status is 'complete', checking if tradebook lookup needed
[2025-12-31 23:35:12,381] INFO in orderstatus_service: [OrderStatus] Order is complete, fetching average price from tradebook
[2025-12-31 23:35:12,528] INFO in order_data: trade_data: [{'LoginID': 'WD4594', 'ClientID': 'WD4594', 'AppOrderID': 1110925155, 'OrderReferenceID': '', 'GeneratedBy': 'TWSAPI', 'ExchangeOrderID': '1300000038531442', 'OrderCategoryType': 'NORMAL', 'ExchangeSegment': 'NSECM', 'ExchangeInstrumentID': 11223, 'OrderSide': 'BUY', 'OrderType': 'Market', 'ProductType': 'MIS', 'TimeInForce': 'DAY', 'OrderPrice': 0, 'OrderQuantity': 101, 'OrderStopPrice': 0, 'OrderStatus': 'Filled', '**OrderAverageTradedPrice': '29.67**', 'LeavesQuantity': 0, 'CumulativeQuantity': 101, 'OrderDisclosedQuantity': 0, 'OrderGeneratedDateTime': '31-12-2025 12:44:41', 'ExchangeTransactTime': '31-12-2025 12:44:41', 'LastUpdateDateTime': '31-12-2025 12:44:41', 'OrderUniqueIdentifier': 'openalgo', 'OrderLegStatus': 'SingleOrderLeg', 'LastTradedPrice': 29.67, 'LastTradedQuantity': 101, 'LastExecutionTransactTime': '31-12-2025 12:44:41', 'ExecutionID': '604502747', 'TradingSymbol': 'UCOBANK', 'ExecutionReportIndex': 3, 'ApiOrderSource': '', 'IsSpread': False, 'MessageCode': 9005, 'MessageVersion': 4, 'TokenID': 0, 'ApplicationType': 0, 'SequenceNumber': 0}, {'LoginID': 'WD4594', 'ClientID': 'WD4594', 'AppOrderID': 1110925181, 'OrderReferenceID': '', 'GeneratedBy': 'TWSAPI', 'ExchangeOrderID': '1300000038795558', 'OrderCategoryType': 'NORMAL', 'ExchangeSegment': 'NSECM', 'ExchangeInstrumentID': 11223, 'OrderSide': 'BUY', 'OrderType': 'Market', 'ProductType': 'MIS', 'TimeInForce': 'DAY', 'OrderPrice': 0, 'OrderQuantity': 101, 'OrderStopPrice': 0, 'OrderStatus': 'Filled', 'OrderAverageTradedPrice': '29.67', 'LeavesQuantity': 0, 'CumulativeQuantity': 101, 'OrderDisclosedQuantity': 0, 'OrderGeneratedDateTime': '31-12-2025 12:46:45', 'ExchangeTransactTime': '31-12-2025 12:46:46', 'LastUpdateDateTime': '31-12-2025 12:46:46', 'OrderUniqueIdentifier': 'openalgo', 'OrderLegStatus': 'SingleOrderLeg', 'LastTradedPrice': 29.67, 'LastTradedQuantity': 101, 'LastExecutionTransactTime': '31-12-2025 12:46:46', 'ExecutionID': '604532510', 'TradingSymbol': 'UCOBANK', 'ExecutionReportIndex': 3, 'ApiOrderSource': '', 'IsSpread': False, 'MessageCode': 9005, 'MessageVersion': 4, 'TokenID': 0, 'ApplicationType': 0, 'SequenceNumber': 0}, {'LoginID': 'WD4594', 'ClientID': 'WD4594', 'AppOrderID': 1110970509, 'OrderReferenceID': '', 'GeneratedBy': 'MobileAndroid', 'ExchangeOrderID': '1300000038922116', 'OrderCategoryType': 'NORMAL', 'ExchangeSegment': 'NSECM', 'ExchangeInstrumentID': 11223, 'OrderSide': 'SELL', 'OrderType': 'Market', 'ProductType': 'MIS', 'TimeInForce': 'DAY', 'OrderPrice': 0, 'OrderQuantity': 202, 'OrderStopPrice': 0, 'OrderStatus': 'Filled', 'OrderAverageTradedPrice': '29.55', 'LeavesQuantity': 0, 'CumulativeQuantity': 202, 'OrderDisclosedQuantity': 0, 'OrderGeneratedDateTime': '31-12-2025 12:47:42', 'ExchangeTransactTime': '31-12-2025 15:00:40', 'LastUpdateDateTime': '31-12-2025 15:00:41', 'OrderUniqueIdentifier': 'Modify on trailing', 'OrderLegStatus': 'SingleOrderLeg', 'LastTradedPrice': 29.55, 'LastTradedQuantity': 202, 'LastExecutionTransactTime': '31-12-2025 15:00:41', 'ExecutionID': '606808326', 'TradingSymbol': 'UCOBANK', 'ExecutionReportIndex': 9, 'ApiOrderSource': '', 'IsSpread': False, 'MessageCode': 9005, 'MessageVersion': 4, 'TokenID': 0, 'ApplicationType': 0, 'SequenceNumber': 0}]       
[2025-12-31 23:35:12,530] INFO in orderstatus_service: [OrderStatus] Searching for OrderID 1110925155 in 3 trades
[2025-12-31 23:35:12,531] WARNING in orderstatus_service: [OrderStatus] No trade found for OrderID 1110925155 in tradebook. Available order IDs: ['1110925155.0', '1110925181.0', '1110970509.0']
[2025-12-31 23:35:12,532] INFO in orderstatus_service: [OrderStatus] LIVE mode - Preparing response for OrderID 1110925155 with status: complete
[2025-12-31 23:35:12,532] INFO in orderstatus_service: [OrderStatus] Successfully processed order status for OrderID 1110925155 - Status: complete, Symbol: UCOBANK, Average Price: 0.0
